version: '2'
services:
  # detector-mqtt
  detector-mqtt:
    hostname: 'detector-mqtt'
    restart: always
    image: __DOCKERHUB_ID__/detector-mqtt_amd64:1.0.0
    networks:
      - detector-network
    ports:
      - '1883:1883'

  # detector-service
  detector-service:
    hostname: 'detector-service'
    restart: always
    image: __DOCKERHUB_ID__/detector-service_amd64:1.0.0
    networks:
      - detector-network
    ports:
      - '5252:80'

  # detector-app
  detector-app:
    hostname: 'detector-app'
    restart: always
    image: __DOCKERHUB_ID__/detector-app_amd64:1.0.0
    networks:
      - detector-network
    environment:
      - "CAM_URL=__CAM_URL__"
      - "DEFAULT_CAM_URL=__DEFAULT_CAM_URL__"
      - "HZN_DEVICE_ID=__HZN_DEVICE_ID__"
      - "SLEEP_BETWEEN_CALLS=__SLEEP_BETWEEN_CALLS__"
      - "EVENTSTREAMS_BROKER_URLS="
      - "EVENTSTREAMS_PUB_TOPIC="
    depends_on:
      - "detector-service"

  # detector-monitor
  detector-monitor:
    hostname: 'detector-monitor'
    restart: always
    image: __DOCKERHUB_ID__/detector-monitor_amd64:1.0.0
    networks:
      - detector-network
    ports:
      - '5200:5200'
    depends_on:
      - "detector-mqtt"
      - "detector-service"

networks:
  detector-network:
    external: true
