FROM python:3.7-alpine

RUN apk --no-cache --update add mosquitto-clients

# Install flask (for the REST API server)
RUN pip install Flask

# Copy the dummy images
COPY *.jpg /

# Copy over the source
RUN mkdir /app
COPY monitor.py /app
COPY templates/ /app/templates

# Run the daemon
CMD ["python", "/app/monitor.py"]
