FROM python:3.7-alpine

WORKDIR /app

# Copy over the source
COPY requirements.txt /app
COPY app.py /app
COPY templates/ /app/templates
COPY static/ /app/static

# Install components
RUN apk update && \
    apk add --no-cache --virtual .build-deps gcc musl-dev && \
    pip install --upgrade pip && \
    pip install -r requirements.txt && \
    apk del .build-deps gcc musl-dev

# Run the daemon
CMD ["python", "app.py"]
