FROM alpine:latest

RUN apk update && \
    apk add --no-cache mosquitto && \
    rm -fr /tmp/* && \
    mkdir -p /var/lib/mosquitto

COPY mosquitto.conf /etc/mosquitto/

CMD ["mosquitto", "-c", "/etc/mosquitto/mosquitto.conf"]
